### PR TITLE
Update chroma_view.xml

### PR DESCRIPTION
**Pull request by DerTyp7214**
now you can only type max 6 hex characters

### CODE REVIEW

**Comment by fonix232** [comment]
@deletescape this looks good to me

**Comment by nyancrimew** [comment]
Will make some adjustments to this to account for ARGB support again as well as the # prefix, lgtm otherwise

**Comment by DerTyp7214** [comment]
i think some code [here](https://github.com/LawnchairLauncher/chroma/blob/master/chroma/src/main/kotlin/me/priyesh/chroma/ChromaView.kt#L83) will be obsolet

**Review by yash-garg — APPROVED** [review]

**Comment by nyancrimew** [comment]
While reviewing this I actually just found an even cleaner way to do this for our case, using InputFilters which allow us to do all of the needed checks in a more dynamic way.

Closing this, will however add you as co-author to my new commit because I wouldn't have found out about this without your help @DerTyp7214

**Comment by nyancrimew** [comment]
see: https://github.com/LawnchairLauncher/chroma/commit/ad570d7dc46d96d701b6491a70b4fa1d8986d9e6

**Pull request closed without merging**
